[package]
name = "typed-eventbus"
version = "0.2.0"
edition = "2024"
description = "Transport-agnostic event streaming with typed events, metadata envelopes, local pub/sub, and NATS support."
license = "MIT"
repository = "https://github.com/Austin-rgb/event-stream"
homepage = "https://github.com/Austin-rgb/event-stream"
documentation = "https://docs.rs/event-stream"
readme = "README.md"
keywords = ["events", "nats", "pubsub", "messaging", "event-driven"]
categories = ["asynchronous", "network-programming"]


[dependencies]
async-nats = "0.47.0"
async-trait = "0.1.89"
futures = "0.3.32"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.51.0"
jiff = { version = "0.2.24", features = ["serde"] }
uuid = { version = "1.23.1", features = ["serde", "v4"] }
thiserror = "2.0.18"
dashmap = "6.2.1"
bytes = "1.11.1"
tracing = "0.1.44"
